site_name: env-diff
site_description: Compares expected environment variables to those set in production.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/env-diff

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
